#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/taoziapp/taoziapp /usr/bin/taoziapp
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/taoziapp.service ]; then
			rm /etc/systemd/system/taoziapp.service /usr/lib/systemd/system/taoziapp.service /usr/lib/systemd/user/taoziapp.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/taoziapp/files/systemd/taoziapp.service /usr/lib/systemd/system/taoziapp.service
		# try fix error in Ubuntu 18.04
		# Failed to reload taoziapp.service: Unit taoziapp.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/taoziapp.service:10: Executable path is not absolute: pkill -f "taoziapp --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/taoziapp.service
		fi
		systemctl daemon-reload
		systemctl enable taoziapp
		systemctl start taoziapp
	fi
fi
